server:
  port: 8080
spring:
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${DB_PASSWORD}
    url: jdbc:mysql://localhost:3306/test_db_board?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8


